name: Demos

on: [push, pull_request]

env:
  Configuration: Release
  ContinuousIntegrationBuild: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: windows-latest
    name: Build demo projects
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Create local NuGet source
        run: |
          $pkgdir = Resolve-Path ..\LocalPackages
          mkdir $pkgdir
          run: dotnet nuget add source $pkgdir --name Local
      - name: Restore NuGet packages
        run: dotnet restore --verbosity normal
      - name: Build library package
        run: dotnet pack --configuration Release --no-restore --verbosity normal
      - name: Install library package
        run: |
          $pkg = Resolve-Path QrCodeGenerator\bin\Release\Net.Codecrete.QrCodeGenerator.*.nupkg
          nuget add QrCodeGenerator\bin\Release\Net.Codecrete.QrCodeGenerator.*.nupkg -Source Local
      - name: Build Demo-ImageSharp
        run: dotnet build
        working-directory: Demo-ImageSharp
